// Blog posts. Slugs match the live site's URLs so existing rankings and links carry over.
// Body blocks: { h2 }, { p }, { ul: [] }, { quote }
export const POSTS = [
  {
    slug: 'emotional-healing-through-grief-guide',
    title: '10 Essential Steps to Emotional Healing Through Grief: A Comprehensive Guide',
    seoTitle: '10 Steps to Emotional Healing Through Grief',
    description:
      'Ten gentle, practical steps toward emotional healing after loss — from acknowledging your grief to finding meaning, support and faith along the way.',
    date: '2025-03-10',
    category: 'Healing',
    keywords: ['emotional healing', 'grief steps', 'coping with loss'],
    related: ['surviving-the-holidays-after-loss', 'faith-based-bereavement-support-guide'],
    body: [
      { p: 'Healing from grief is rarely a straight line. Some days feel lighter; others bring waves you did not see coming. These ten steps are not a checklist to finish — they are companions for the road, to return to whenever you need them.' },
      { h2: '1. Acknowledge your grief' },
      { p: 'Naming what you feel — sadness, anger, numbness, even relief — is the first act of healing. Grief that is acknowledged can begin to move.' },
      { h2: '2. Give yourself permission to feel' },
      { p: 'There is no “right” way to grieve. Tears, silence, laughter and exhaustion can all live side by side.' },
      { h2: '3. Seek professional support' },
      { p: 'A **certified grief coach** or counselor offers structure and a safe space to process what you are carrying, especially when you feel stuck. Learn [how to find a grief coach](/blog/how-to-find-a-grief-coach-a-compassionate-guide-to-healing) or explore [grief coaching in Berlin, MD](/personalized-grief-coaching-support-berlin-md).' },
      { h2: '4. Create safe spaces for expression' },
      { p: 'Journaling, art, music, prayer or a trusted friend can all become places where your grief is welcome.' },
      { h2: '5. Care for your body' },
      { p: 'Grief is physical. Gentle movement, water, nourishing food and rest help your body carry the emotional load.' },
      { h2: '6. Prepare for hard days' },
      { p: 'Anniversaries, birthdays and [holidays](/blog/surviving-the-holidays-after-loss) deserve a plan. Decide ahead of time what you need and who you want nearby.' },
      { h2: '7. Stay connected' },
      { p: 'Isolation can deepen pain. **Grief support groups** and community — in person or online — remind you that you are not alone.' },
      { h2: '8. Honor your loved one' },
      { p: 'Rituals, legacy projects and simply saying their name keep love present while you learn to live forward.' },
      { h2: '9. Find meaning through faith' },
      { p: 'For many, prayer, Scripture and a faith community provide comfort, hope and perspective in the darkest seasons — see our [faith-based bereavement support guide](/blog/faith-based-bereavement-support-guide).' },
      { h2: '10. Be patient with yourself' },
      { p: '**Emotional healing through grief** is not forgetting. It is learning to carry love and loss together — at your own pace.' },
      { quote: 'You do not have to walk this road alone. Support is available whenever you are ready.' },
    ],
  },
  {
    slug: 'grief-coaching-techniques-for-healing',
    title: 'Effective Grief Coaching Techniques for Healing: A Comprehensive Guide',
    seoTitle: 'Effective Grief Coaching Techniques for Healing',
    description:
      'How professional grief coaching blends emotional support, practical strategies and proven tools to help you move forward while honoring your loss.',
    date: '2025-02-18',
    category: 'Grief Coaching',
    keywords: ['grief coaching techniques', 'grief coach', 'healing after loss'],
    related: ['how-to-find-a-grief-coach-a-compassionate-guide-to-healing', 'emotional-healing-through-grief-guide'],
    body: [
      { p: '**Grief coaching** offers structured guidance and compassionate support that can help transform pain into meaningful healing. Here are some of the techniques coaches use — and why they work.' },
      { h2: 'Compassionate listening' },
      { p: 'Everything begins with being heard. A coach holds space for your story without judgment or rushing you toward “closure.”' },
      { h2: 'Goal-setting that honors your pace' },
      { p: 'Small, realistic goals — getting through a weekend, sorting one drawer, attending one gathering — create momentum without pressure.' },
      { h2: 'Reframing and meaning-making' },
      { p: 'Coaches help you explore new ways of understanding your loss, so that love and memory can shape a hopeful future.' },
      { h2: 'Grounding and breath work' },
      { p: 'Frameworks like the **B.R.E.A.T.H.E. model** use intentional pauses and breathing to calm the body when emotions feel overwhelming.' },
      { h2: 'Practical life planning' },
      { p: 'From new routines to difficult decisions, coaching provides tools to navigate the practical changes loss brings.' },
      { h2: 'Is coaching right for you?' },
      { ul: ['You feel stuck or unsure how to move forward', 'You want structure and accountability', 'You are ready to explore hope, even alongside sadness'] },
      { p: 'If any of these sound familiar, a [free consultation](/contact-toni-ward-for-grief-coaching-support) is a gentle place to start. You can also read about [individual grief support](/individual-grief-counseling-support-in-berlin-md).' },
    ],
  },
  {
    slug: 'how-to-find-a-grief-coach-a-compassionate-guide-to-healing',
    title: 'How to Find a Grief Coach: A Compassionate Guide to Healing',
    description:
      'What grief coaching is, who it helps and the questions to ask as you look for the right grief coach for your journey.',
    date: '2025-01-22',
    category: 'Grief Coaching',
    keywords: ['find a grief coach', 'grief coach near me', 'grief coaching Maryland'],
    related: ['grief-coaching-techniques-for-healing', 'discovering-the-best-faith-based-grief-recovery-programs-a-compassionate-comparison'],
    body: [
      { p: '**Grief coaching** focuses on healing and moving forward while honoring your loss. It can be especially helpful if you feel stuck. Here is how to find a coach who is the right fit.' },
      { h2: 'Look for training and lived experience' },
      { p: 'Ask about certifications, the model or framework (for example, the **B.R.E.A.T.H.E. model**) the coach uses and the settings they have worked in, such as hospices, funeral homes or churches.' },
      { h2: 'Consider your preferred format' },
      { p: 'Do you want in-person sessions, secure online video, or both? **Online grief coaching** makes support accessible from anywhere — Toni offers both from [Berlin, MD](/personalized-grief-coaching-support-berlin-md).' },
      { h2: 'Ask the right questions' },
      { ul: ['What does a typical session look like?', 'How do you tailor coaching to my loss?', 'Do you incorporate faith if I want that?', 'How many sessions do clients usually have?'] },
      { h2: 'Trust how you feel' },
      { p: 'The most important factor is feeling safe and understood. See [effective grief coaching techniques](/blog/grief-coaching-techniques-for-healing), then book a [complimentary consultation](/contact-toni-ward-for-grief-coaching-support) lets you experience that before you commit.' },
    ],
  },
  {
    slug: 'faith-based-bereavement-support-guide',
    title: 'Navigating Grief: The Essential Guide to Faith-Based Bereavement Support',
    seoTitle: 'Faith-Based Bereavement Support: An Essential Guide',
    description:
      'How spiritual practices, Scripture and faith communities can help you process the emotional, physical and spiritual impact of grief.',
    date: '2024-12-05',
    category: 'Faith & Grief',
    keywords: ['faith-based bereavement support', 'christian grief support', 'grief and faith'],
    related: ['discovering-the-best-faith-based-grief-recovery-programs-a-compassionate-comparison', 'emotional-healing-through-grief-guide'],
    body: [
      { p: 'Faith and grief often meet in the same heart. For many people, belief brings comfort and hope — and sometimes hard questions. **Faith-based bereavement support** makes room for both.' },
      { h2: 'Grief touches every part of us' },
      { ul: ['Emotional: sorrow, anxiety, anger, guilt', 'Physical: fatigue, poor sleep, changes in appetite', 'Spiritual: questions about meaning, God and the future'] },
      { h2: 'Practices that nurture the soul' },
      { p: 'Prayer, meditation and Scripture study can provide strength for each day. Many people find comfort in writing prayers or keeping a gratitude-and-lament journal.' },
      { h2: 'The gift of community' },
      { p: 'Faith-based **grief support groups** and congregations offer shared encouragement and practical help during the hardest seasons. Compare options in [faith-based grief recovery programs](/blog/discovering-the-best-faith-based-grief-recovery-programs-a-compassionate-comparison).' },
      { h2: 'Support options' },
      { p: 'Toni Ward Grief Coaching offers faith-informed [1:1 coaching](/personalized-grief-coaching-support-berlin-md), groups and [workshops](/public-speaking-workshops) for those who want their faith to be part of the healing conversation.' },
    ],
  },
  {
    slug: 'discovering-the-best-faith-based-grief-recovery-programs-a-compassionate-comparison',
    title: 'Discovering the Best Faith-Based Grief Recovery Programs: A Compassionate Comparison',
    seoTitle: 'Best Faith-Based Grief Recovery Programs Compared',
    description:
      'A gentle comparison of faith-based grief recovery options — church groups, structured programs and one-on-one coaching — to help you choose what fits.',
    date: '2024-11-12',
    category: 'Faith & Grief',
    keywords: ['faith-based grief recovery programs', 'grief support groups', 'christian grief coaching'],
    related: ['faith-based-bereavement-support-guide', 'how-to-find-a-grief-coach-a-compassionate-guide-to-healing'],
    body: [
      { p: 'Choosing a **faith-based grief recovery program** is personal. Here is a simple way to compare common faith-based options.' },
      { h2: 'Church-based support groups' },
      { p: 'Often free and rooted in community. Great for connection, though groups may follow a fixed schedule and curriculum.' },
      { h2: 'Structured multi-week programs' },
      { p: 'Offer a clear path through grief topics week by week. Helpful if you like structure and learning alongside others.' },
      { h2: 'One-on-one faith-informed coaching' },
      { p: '[Personalized grief coaching](/personalized-grief-coaching-support-berlin-md) is tailored to your story, pace and goals. Ideal if your loss is complex, you feel stuck, or you want private support.' },
      { h2: 'Questions to ask' },
      { ul: ['Do I want group connection or private support?', 'How much structure do I need?', 'Is in-person or online easier right now?'] },
      { p: 'Many people combine options — for example, joining a group while also working with a coach. Not sure where to start? Read [how to find a grief coach](/blog/how-to-find-a-grief-coach-a-compassionate-guide-to-healing).' },
    ],
  },
  {
    slug: 'surviving-the-holidays-after-loss',
    title: 'Surviving the Holidays After Loss: Gentle Strategies for Grieving Hearts',
    seoTitle: 'Surviving the Holidays After Loss: Gentle Strategies',
    description:
      'Practical, compassionate ideas for getting through holidays, anniversaries and special days while grieving.',
    date: '2024-11-01',
    category: 'Healing',
    keywords: ['grief during holidays', 'holidays after loss', 'widow holidays'],
    related: ['emotional-healing-through-grief-guide', 'how-to-find-a-grief-coach-a-compassionate-guide-to-healing'],
    body: [
      { p: '**Grief during the holidays** can magnify the absence of someone we love. A little planning and a lot of self-compassion can make these days more bearable.' },
      { h2: 'Make a plan — and a backup plan' },
      { p: 'Decide which traditions you want to keep, change or skip this year. Give yourself permission to leave early.' },
      { h2: 'Create a new ritual' },
      { p: 'Light a candle, share favorite stories, or set a place in their honor. Rituals let love have a place at the table.' },
      { h2: 'Tell people what you need' },
      { p: 'Friends and family often want to help but do not know how. A simple, honest request goes a long way.' },
      { h2: 'Rest and reach out' },
      { p: 'Protect your energy, and lean on support — a group, your faith community or a [grief coach](/personalized-grief-coaching-support-berlin-md). Widowed? See [widow support in Berlin, MD](/widow-loss-counseling-support-in-berlin-md).' },
    ],
  },
];

export const getPost = (slug) => POSTS.find((p) => p.slug === slug);
